[package]
name = "vgonio"
version = "0.3.0"
authors = ["Yang Chen <y.chen-14@tudelft.nl>"]
edition = "2021"
build = "build.rs"
description = "Microscopic level light transport simulation."
publish = false

[dependencies]
approx = "0.5"
bincode = "1"
bytemuck = { version = "1.12", features = ["derive"] }
byteorder = "1"
cfg-if = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
csv = "1"
dirs = "5.0"
egui = { version = "0.21", features = ["bytemuck"] }
egui_extras = "0.21"
egui-winit = { version = "0.21", default-features = false }
egui-gizmo = "0.10"
embree = { git = "https://github.com/matthiascy/embree-rs.git", branch = "own", optional = true}
env_logger = "0.10"
flate2 = "1.0"
futures-intrusive = "0.5"
glam = { version = "0.22", features = ["serde", "bytemuck"] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
itertools = "0.10"
log = "0.4"
paste = "1.0"
pollster = "0.3"
rfd = { version = "0.11", features = ["file-handle-inner"] }
rayon = "1.6"
rand = "0.8"
rand_distr = "0.4"
rand_chacha = "0.3"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
toml = "0.7"
type-map = "0.5"
uuid = { version = "1.2", features = ["serde", "v4"] }
winit = "0.28"
wgpu = { version = "0.16", features = ["spirv"] }

[features]
default = []
embree = ["dep:embree"]
optix = []

[build-dependencies]
shaderc = "0.8"

[dev-dependencies]
proptest = "1"

[profile.dev]
split-debuginfo = "unpacked"
[profile.dev.build-override]
opt-level = 3

[profile.release]
strip = "debuginfo"  # Remove unnecessary debug info from release builds.
lto = true  # Enable link-time optimization.
# debug = 1  # Keep debug info in release builds for profiling.

# Compile build-dependencies in release mode with
# the same settings as regular dependencies.
[profile.release.build-override]
opt-level = 3
codegen-units = 16
