[package]
name = "vgonio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
winit = "0.26"
glam = { version = "0.20", features = ["serde", "bytemuck"] }
env_logger = "0.9"
log = "0.4"
wgpu = { version = "0.12" }
pollster = "0.2"
bytemuck = "1.7"
clap = { version = "3", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
bincode = "1"
byteorder = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
egui = { version = "0.17", features = ["convert_bytemuck"]}
epi = "0.17"
egui_demo_lib = "0.17"
egui-winit = "0.17"
egui-gizmo = "0.6"
rfd = "0.8"

[dev-dependencies]
quickcheck = "1"