[package]
name = "vgonio"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.24"
winit = "0.26"
glam = { version = "0.20", features = ["serde", "bytemuck"] }
env_logger = "0.9"
log = "0.4"
wgpu = { version = "0.12", features = ["spirv"] }
pollster = "0.2"
bytemuck = { version = "1.7", features = ["derive"] }
clap = { version = "3", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
bincode = "1"
byteorder = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
egui = { version = "0.17", features = ["convert_bytemuck"]}
epi = "0.17"
egui_demo_lib = "0.17"
egui-winit = "0.17"
egui-gizmo = "0.6"
rfd = "0.8"
rayon = "1.5"
chrono = "0.4"
dirs = "4.0"
toml = "0.5"
csv = "1"
embree = { git = "https://github.com/matthiascy/embree-rs.git", branch = "own" }

[build-dependencies]
shaderc = "0.7"

# Compile build-dependencies in release mode with
# the same settings as regular dependencies.
[profile.release.build-override]
opt-level = 3
codegen-units = 16

[profile.release]
strip = "debuginfo"  # Remove unnecessary debug info from release builds.

[profile.dev.build-override]
opt-level = 3

[dev-dependencies]
quickcheck = "1"