[package]
name = "vgonio"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.24"
winit = "0.26"
glam = { version = "0.21", features = ["serde", "bytemuck"] }
env_logger = "0.9"
log = "0.4"
wgpu = { version = "0.13", features = ["spirv"] }
pollster = "0.2"
bytemuck = { version = "1.7", features = ["derive"] }
clap = { version = "3", features = ["derive"] }
uuid = { version = "1.1", features = ["serde", "v4"] }
bincode = "1"
byteorder = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
egui = { version = "0.18", features = ["bytemuck"] }
egui_demo_lib = "0.18"
egui-winit = "0.18.0"
egui-gizmo = "0.7"
futures-intrusive = "0.4"
rfd = "0.10"
rayon = "1.5"
chrono = "0.4"
dirs = "4.0"
toml = "0.5"
csv = "1"
rand = "0.8"
rand_distr = "0.4"
embree = { git = "https://github.com/matthiascy/embree-rs.git", branch = "own" }
paste = "1.0"

[build-dependencies]
shaderc = "0.8"

# Compile build-dependencies in release mode with
# the same settings as regular dependencies.
[profile.release.build-override]
opt-level = 3
codegen-units = 16

[profile.release]
strip = "debuginfo"  # Remove unnecessary debug info from release builds.

[profile.dev.build-override]
opt-level = 3

[dev-dependencies]
quickcheck = "1"