reorder_imports = true
imports_granularity = "Crate"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
newline_style = "Unix"
wrap_comments = true
match_block_trailing_comma = true
