[package]
name = "vgonio-serve"
authors.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
version.workspace = true

[dependencies]

[lints]
workspace = true
