upstream = "https://github.com/polyanskiy/refractiveindex.info-database"

[[dataset]]
file = "air_Ciddor1996.ior.ron"
medium = "air"
default = true
path = "other/mixed gases/air/nk/Ciddor.yml"
verified = true

[[dataset]]
file = "al_McPeak2015.ior.ron"
medium = "al"
default = true
path = "main/Al/nk/McPeak.yml"
verified = true

[[dataset]]
file = "al_Cheng2016.ior.ron"
medium = "al"
default = false
path = "main/Al/nk/Cheng.yml"
verified = true

[[dataset]]
file = "cu_McPeak2015.ior.ron"
medium = "cu"
default = true
path = "main/Cu/nk/McPeak.yml"
verified = true

[[dataset]]
file = "ni_Johnson1974.ior.ron"
medium = "ni"
default = true
path = "main/Ni/nk/Johnson.yml"
verified = true

[[dataset]]
file = "cr_Johnson1974.ior.ron"
medium = "cr"
default = true
path = "main/Cr/nk/Johnson.yml"
verified = true

[[dataset]]
file = "pvc_Zhang2020.ior.ron"
medium = "pvc"
default = true
path = "organic/(C2H3Cl)n - polyvinyl chloride/nk/Zhang.yml"
verified = true
