//! Structured events emitted around a job's execution.
//!
//! Two orthogonal axes ride on the same channel:
//!
//! - **Lifecycle** ([`Lifecycle`]): the job's state machine as a whole. Owned by the executor;
//!   handlers MUST NOT emit lifecycle events. Exactly one terminal lifecycle event
//!   ([`Lifecycle::Completed`] / [`Lifecycle::Failed`] / [`Lifecycle::Cancelled`]) is emitted per
//!   job.
//! - **Activity** ([`Activity`]): the structured stream of what is happening inside the job. Owned
//!   by the handler via `ctx.progress`. Phases form a tree per job; messages, ratios, and warnings
//!   attach to the phase they happened in.
//!
//! Both ride on a single [`JobEvent`] union so the wire stream is one
//! ordered sequence, but the types are split so the borrow checker enforces
//! who emits what.
//!
//! # Lifecycle ordering
//!
//! ```text
//! Lifecycle::Queued       -- enqueued by the executor (optional)
//!   -> Lifecycle::Started   -- worker picked up the job
//!     -> Activity::PhaseBegin / PhaseEnd / Message / Progress / Warning
//!        (zero or more, interleaved freely; phases nest)
//!     -> one terminal Lifecycle event:
//!          Lifecycle::Completed   -- normal success
//!          Lifecycle::Failed      -- carries the JobError
//!          Lifecycle::Cancelled   -- client-initiated abort
//! ```
//!
//! Receivers must tolerate [`Lifecycle::Started`] arriving without a preceding
//! [`Lifecycle::Queued`] (synchronous executors skip the queue), and must
//! treat any event after the terminal as a protocol violation.
//!
//! # Why `Failed` carries the error
//!
//! Earlier drafts considered emitting `Failed` *and* returning a separate
//! `Result` on a result channel. Storing the same error in two places invites
//! disagreement between them on the wire, so the progress stream is the
//! single source of truth: [`JobError`] is nested directly into
//! [`Lifecycle::Failed`].
//!
//! # Open-phase reconciliation
//!
//! If a job reaches [`Lifecycle::Failed`] or [`Lifecycle::Cancelled`] with
//! phases still open (an [`Activity::PhaseBegin`] with no matching
//! [`Activity::PhaseEnd`]), receivers MUST treat every open phase as
//! implicitly ended at this lifecycle event's `at`, with outcome
//! [`PhaseOutcome::Failed`] (carrying the terminal error) or a synthetic
//! [`PhaseOutcome::Skipped`] respectively. The handler is not required to
//! emit synthetic `PhaseEnd`s; the receiver reconciles.

use crate::{error::JobError, ids::JobId};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Per-job phase identity, generated by the handler context.
///
/// Monotonically increasing within one job; never reused across runs.
/// Receivers use this to pair [`Activity::PhaseBegin`] with
/// [`Activity::PhaseEnd`] and to build the parent / child phase tree.
///
/// `u32` covers any realistic emitter: 4 billion phases per job is well
/// beyond per-patch-loop usage. If a handler approaches that, it is
/// emitting too often and should aggregate before sending.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PhaseInstanceId(pub u32);

/// Stable, namespaced phase kind.
///
/// Wire format is a dotted string with the owning capability as the first
/// segment: `"measure.load_surfaces"`, `"fit.brdf.brute_force"`. Two
/// capabilities cannot collide as long as they keep to their own prefix.
/// Constants for the built-in capabilities are below; new kinds can be
/// minted freely but should be documented in the capability's design doc
/// so dashboards have something to bind to.
///
/// # Identity model
///
/// `kind` is the *type* of phase ("a load-surfaces operation"); it is
/// stable across runs and forms the key for log grep, cross-run
/// benchmarking, and Prometheus-style labels. [`PhaseInstanceId`] is the
/// *instance* ("this particular load-surfaces in this particular run");
/// it is generated per phase and used only for in-run pairing and
/// nesting. Two phases with the same `kind` are explicitly allowed (a
/// loop emitting one phase per iteration is the canonical example).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PhaseKind(pub String);

impl PhaseKind {
    // ---------------- fit (vgonio fit ...) ----------------

    /// Top-level NDF fitting.
    pub fn fit_ndf() -> Self { Self("fit.ndf".into()) }

    /// Top-level BRDF fitting.
    pub fn fit_brdf() -> Self { Self("fit.brdf".into()) }

    /// Per-input load + fit pass under `fit.brdf`.
    pub fn fit_brdf_measured() -> Self { Self("fit.brdf.measured".into()) }

    /// Clausen-pair resampling under `fit.brdf`.
    pub fn fit_brdf_clausen_resample() -> Self { Self("fit.brdf.clausen_resample".into()) }

    /// Brute-force grid search under `fit.brdf.measured`.
    pub fn fit_brdf_brute_force() -> Self { Self("fit.brdf.brute_force".into()) }

    /// Per-wavelength brute-force iteration under `fit.brdf.brute_force`.
    pub fn fit_brdf_brute_force_per_wavelength() -> Self {
        Self("fit.brdf.brute_force.per_wavelength".into())
    }

    /// GPU memory pre-allocation under `fit.brdf.brute_force`.
    pub fn fit_brdf_brute_force_gpu_prealloc() -> Self {
        Self("fit.brdf.brute_force.gpu_prealloc".into())
    }

    /// Nllsq (nonlinear least squares) fitter under `fit.brdf.measured`.
    pub fn fit_brdf_nllsq() -> Self { Self("fit.brdf.nllsq".into()) }

    // ---------------- measure (vgonio measure ...) ----------------

    /// Top-level measurement phase.
    pub fn measure_root() -> Self { Self("measure".into()) }

    /// Reading measurement description files.
    pub fn measure_read_descriptions() -> Self { Self("measure.read_descriptions".into()) }

    /// Loading shared data files (IOR / spectral data) needed by BSDF.
    pub fn measure_load_iors() -> Self { Self("measure.load_iors".into()) }

    /// Resolving and loading the micro-surface files referenced by the
    /// loaded descriptions.
    pub fn measure_load_surfaces() -> Self { Self("measure.load_surfaces".into()) }

    /// Per-description BSDF measurement.
    pub fn measure_bsdf() -> Self { Self("measure.bsdf".into()) }

    /// Per-description NDF measurement.
    pub fn measure_ndf() -> Self { Self("measure.ndf".into()) }

    /// Per-description MSF (masking-shadowing) measurement.
    pub fn measure_msf() -> Self { Self("measure.msf".into()) }

    /// Per-description SDF (slope distribution) measurement.
    pub fn measure_sdf() -> Self { Self("measure.sdf".into()) }

    /// Writing measurement outputs to disk.
    pub fn measure_write_output() -> Self { Self("measure.write_output".into()) }

    /// Returns the raw wire string.
    pub fn as_str(&self) -> &str { &self.0 }
}

/// Outcome reported on [`Activity::PhaseEnd`]. The renderer picks glyphs
/// and colors from this; the handler does not encode rendering intent in
/// prose.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum PhaseOutcome {
    /// Phase completed normally.
    Ok,
    /// Phase did not run because preconditions were not met. The reason
    /// is human-readable (`"no inputs to load"`); machine consumers
    /// should not parse it, only display it.
    Skipped { reason: String },
    /// Phase ran but some sub-items failed. The handler chose to
    /// continue; the renderer shows a warning glyph.
    PartialFailure { detail: String },
    /// Phase aborted with an error; the handler bubbled the error up via
    /// `Result::Err`. Receivers that see this outcome inside a phase's
    /// `PhaseEnd` should expect the job's terminal
    /// [`Lifecycle::Failed`] with the same `error` shortly after.
    Failed { error: JobError },
}

/// What an [`Activity::Progress`] `fraction` is measuring against.
///
/// Carries the total count so consumers can render
/// "47% (62/132 patches)" without out-of-band state.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum ProgressUnits {
    /// Counting discrete items (patches, samples, files).
    Items { total: u64 },
    /// Counting bytes (file I/O, network transfer).
    Bytes { total: u64 },
    /// Generic 0..1 ratio with no underlying count. Use when there is no
    /// natural unit (e.g., a brute-force search reporting
    /// "37% of the grid").
    Ratio,
    /// Counting discrete sub-steps inside a phase (stage 1 of N).
    Steps { total: u32 },
}

/// Handler-emitted activity inside the job. Sent via `ctx.progress`; the
/// executor does not synthesize these.
///
/// Every variant except [`Self::PhaseBegin`] carries the `phase` of the
/// instance it belongs to. `PhaseBegin` itself is the boundary that
/// introduces a new instance; its `parent` references the enclosing
/// phase (or `None` for top-level phases of this job).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum Activity {
    /// Open a phase. The matching [`Self::PhaseEnd`] MUST carry the same
    /// `instance` and be emitted before any terminal [`Lifecycle`] event.
    PhaseBegin {
        /// Unique within this job, generated by the handler context.
        instance: PhaseInstanceId,
        /// Enclosing phase, or `None` for a top-level phase.
        parent: Option<PhaseInstanceId>,
        /// Stable namespaced kind (see [`PhaseKind`]).
        kind: PhaseKind,
        /// Free-form human label for the renderer. Not parsed; use
        /// `kind` for routing.
        label: String,
        /// UTC instant the phase opened.
        at: DateTime<Utc>,
    },
    /// Close a phase. Pairs with [`Self::PhaseBegin`] on `instance`.
    PhaseEnd {
        instance: PhaseInstanceId,
        outcome: PhaseOutcome,
        /// Wall-clock elapsed from this phase's `PhaseBegin.at` to this
        /// emission, in microseconds. Stored here (not derived from
        /// timestamps) so distributed workers report their own elapsed,
        /// not transport jitter, and each event is self-describing for
        /// log consumers.
        duration_micros: Option<u64>,
        /// Optional one-line summary for the renderer
        /// (`"12 surfaces (3 skipped)"`). Not parsed.
        summary: Option<String>,
        /// UTC instant the phase closed.
        at: DateTime<Utc>,
    },
    /// Free-form informational message attached to a phase. Use
    /// [`Self::Warning`] for abnormal-but-non-fatal conditions.
    Message {
        phase: PhaseInstanceId,
        /// Syslog-style severity hint, conventionally:
        /// `0` = emerg, `4` = warning, `6` = info, `7` = debug.
        /// The bridge gates rendering on verbosity.
        level: u8,
        text: String,
    },
    /// Ratio-based progress tick within a phase. The emitter is
    /// responsible for throttling: do not emit per iteration of a hot
    /// loop. Receivers clamp `fraction` to `[0, 1]` and tolerate `NaN`
    /// by treating it as `0`.
    Progress {
        phase: PhaseInstanceId,
        fraction: f32,
        units: ProgressUnits,
        /// Optional human-readable note (`"patch 12/48"`).
        label: Option<String>,
    },
    /// Non-fatal abnormal condition attached to a phase. The phase will
    /// continue (or already has); set the phase's `PhaseEnd.outcome` to
    /// [`PhaseOutcome::PartialFailure`] if the warning meant some
    /// sub-work was dropped.
    Warning {
        phase: PhaseInstanceId,
        text: String,
    },
}

/// Job state machine, owned by the executor. The handler MUST NOT emit
/// these; the executor synthesizes them around the handler call.
///
/// Exactly one terminal event ([`Self::Completed`], [`Self::Failed`], or
/// [`Self::Cancelled`]) per job. Receivers MUST treat any event after the
/// terminal as a protocol violation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum Lifecycle {
    /// Envelope accepted into the run queue; no worker has picked it up.
    /// Optional: synchronous executors skip straight to
    /// [`Self::Started`].
    Queued { at: DateTime<Utc> },
    /// Worker began executing the handler.
    Started { at: DateTime<Utc> },
    /// Terminal: handler returned successfully.
    Completed { at: DateTime<Utc> },
    /// Terminal: handler returned an error. Reconciles open phases.
    Failed { at: DateTime<Utc>, error: JobError },
    /// Terminal: cancelled by client request or executor deadline.
    Cancelled { at: DateTime<Utc> },
}

/// Union of lifecycle + activity, the single stream that rides on the
/// `JobHandle::events` channel. The `channel` discriminator names the
/// owning side so consumers can route without inspecting the inner
/// variant.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "channel", content = "event", rename_all = "snake_case")]
#[non_exhaustive]
pub enum JobEvent {
    Lifecycle(Lifecycle),
    Activity(Activity),
}

/// Wire wrapper that pairs a [`JobEvent`] with the [`JobId`] it belongs
/// to. In-process channels do not need this (the receiver already knows
/// the job); distributed transports wrap events to demux multiple jobs
/// over one connection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobEventEnvelope {
    pub job_id: JobId,
    pub event: JobEvent,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::JobErrorCode;

    fn ts() -> DateTime<Utc> {
        DateTime::parse_from_rfc3339("2026-01-01T00:00:00Z")
            .unwrap()
            .with_timezone(&Utc)
    }

    fn rt_json<T>(value: &T)
    where
        T: Serialize + for<'a> Deserialize<'a>,
    {
        let json = serde_json::to_string(value).unwrap();
        let back: T = serde_json::from_str(&json).unwrap();
        let json_back = serde_json::to_string(&back).unwrap();
        assert_eq!(json, json_back, "round-trip changed wire bytes");
    }

    fn err() -> JobError {
        JobError {
            code: JobErrorCode::HandlerError,
            message: "boom".into(),
            retriable: false,
            details: None,
        }
    }

    #[test]
    fn lifecycle_each_variant_roundtrips() {
        for ev in [
            Lifecycle::Queued { at: ts() },
            Lifecycle::Started { at: ts() },
            Lifecycle::Completed { at: ts() },
            Lifecycle::Failed {
                at: ts(),
                error: err(),
            },
            Lifecycle::Cancelled { at: ts() },
        ] {
            rt_json(&ev);
        }
    }

    #[test]
    fn activity_each_variant_roundtrips() {
        let phase = PhaseInstanceId(1);
        rt_json(&Activity::PhaseBegin {
            instance: phase,
            parent: None,
            kind: PhaseKind::measure_load_surfaces(),
            label: "Loading 12 surfaces".into(),
            at: ts(),
        });
        rt_json(&Activity::PhaseEnd {
            instance: phase,
            outcome: PhaseOutcome::Ok,
            duration_micros: Some(340_000),
            summary: Some("12 surfaces (0 skipped)".into()),
            at: ts(),
        });
        rt_json(&Activity::Message {
            phase,
            level: 0,
            text: "Reading file foo.surf".into(),
        });
        rt_json(&Activity::Progress {
            phase,
            fraction: 0.5,
            units: ProgressUnits::Items { total: 132 },
            label: Some("patch 66/132".into()),
        });
        rt_json(&Activity::Warning {
            phase,
            text: "skipped 1 unreadable surface".into(),
        });
    }

    #[test]
    fn phase_outcome_each_variant_roundtrips() {
        rt_json(&PhaseOutcome::Ok);
        rt_json(&PhaseOutcome::Skipped {
            reason: "no inputs".into(),
        });
        rt_json(&PhaseOutcome::PartialFailure {
            detail: "3 of 12 failed".into(),
        });
        rt_json(&PhaseOutcome::Failed { error: err() });
    }

    #[test]
    fn progress_units_each_variant_roundtrips() {
        rt_json(&ProgressUnits::Items { total: 132 });
        rt_json(&ProgressUnits::Bytes { total: 1_048_576 });
        rt_json(&ProgressUnits::Ratio);
        rt_json(&ProgressUnits::Steps { total: 4 });
    }

    #[test]
    fn progress_units_wire_shape_is_tagged() {
        let v = serde_json::to_value(ProgressUnits::Items { total: 100 }).unwrap();
        assert_eq!(v.get("type").and_then(|s| s.as_str()), Some("items"));
        assert_eq!(v.get("total").and_then(|n| n.as_u64()), Some(100));

        let v = serde_json::to_value(ProgressUnits::Ratio).unwrap();
        assert_eq!(v.get("type").and_then(|s| s.as_str()), Some("ratio"));
    }

    #[test]
    fn phase_kind_constants_are_namespaced() {
        for k in all_phase_kinds() {
            let s = k.as_str();
            assert!(s.contains('.'), "PhaseKind {s:?} should be namespaced");
            let prefix = s.split('.').next().unwrap();
            assert!(
                matches!(prefix, "fit" | "measure"),
                "PhaseKind {s:?} should start with a capability prefix"
            );
        }
    }

    #[test]
    fn phase_kind_constants_have_unique_wire_strings() {
        let mut seen = std::collections::HashSet::new();
        for k in all_phase_kinds() {
            assert!(
                seen.insert(k.as_str().to_owned()),
                "duplicate kind: {}",
                k.as_str()
            );
        }
    }

    fn all_phase_kinds() -> [PhaseKind; 16] {
        [
            PhaseKind::fit_ndf(),
            PhaseKind::fit_brdf(),
            PhaseKind::fit_brdf_measured(),
            PhaseKind::fit_brdf_clausen_resample(),
            PhaseKind::fit_brdf_brute_force(),
            PhaseKind::fit_brdf_brute_force_per_wavelength(),
            PhaseKind::fit_brdf_brute_force_gpu_prealloc(),
            PhaseKind::fit_brdf_nllsq(),
            PhaseKind::measure_read_descriptions(),
            PhaseKind::measure_load_iors(),
            PhaseKind::measure_load_surfaces(),
            PhaseKind::measure_bsdf(),
            PhaseKind::measure_ndf(),
            PhaseKind::measure_msf(),
            PhaseKind::measure_sdf(),
            PhaseKind::measure_write_output(),
        ]
    }

    #[test]
    fn job_event_union_roundtrips_each_arm() {
        rt_json(&JobEvent::Lifecycle(Lifecycle::Started { at: ts() }));
        rt_json(&JobEvent::Activity(Activity::Message {
            phase: PhaseInstanceId(1),
            level: 6,
            text: "info".into(),
        }));
    }

    #[test]
    fn job_event_wire_shape_carries_channel_discriminator() {
        let v =
            serde_json::to_value(JobEvent::Lifecycle(Lifecycle::Completed { at: ts() })).unwrap();
        assert_eq!(v.get("channel").and_then(|s| s.as_str()), Some("lifecycle"));
        assert!(
            v.get("event").is_some(),
            "channel-tagged content must keep event"
        );

        let v = serde_json::to_value(JobEvent::Activity(Activity::Warning {
            phase: PhaseInstanceId(7),
            text: "skipped".into(),
        }))
        .unwrap();
        assert_eq!(v.get("channel").and_then(|s| s.as_str()), Some("activity"));
    }

    #[test]
    fn job_event_envelope_roundtrips() {
        let env = JobEventEnvelope {
            job_id: JobId::new(),
            event: JobEvent::Activity(Activity::PhaseEnd {
                instance: PhaseInstanceId(42),
                outcome: PhaseOutcome::Ok,
                duration_micros: Some(12_345),
                summary: None,
                at: ts(),
            }),
        };
        let json = serde_json::to_string(&env).unwrap();
        let back: JobEventEnvelope = serde_json::from_str(&json).unwrap();
        assert_eq!(env.job_id, back.job_id);
        assert_eq!(
            serde_json::to_string(&env.event).unwrap(),
            serde_json::to_string(&back.event).unwrap(),
        );
    }
}
