[alias]
b = "build"
bef = "build --features fitting"
bdbg = "build --features debug,fitting,verbose-dbg"
r = "run"
ref = "build --features fitting"
rdbg = "build --features debug,fitting,verbose-dbg"
opt = "build --features fitting"
vis = "build --features visu-dbg"

[build]
rustc-wrapper = "sccache"
rustdocflags = ["--html-in-header", "./misc/docs-header.html"]
rustflags = ["-Clink-arg=-fuse-ld=mold"]
