[alias]
b = "build"
bef = "build --features embree,fitting"
bdbg = "build --features debug,embree,fitting,verbose-dbg"
r = "run"
ref = "build --features embree,fitting"
rdbg = "build --features debug,embree,fitting,verbose-dbg"
opt = "build --features embree,fitting"
vis = "build --features embree,visu-dbg"

[build]
rustc-wrapper = "sccache"
rustdocflags = ["--html-in-header", "./misc/docs-header.html"]
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Zthreads=12"]
