[package]
name = "vgonio-bxdf"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
libm.workspace = true
num-traits.workspace = true
vgcore = { package = "vgonio-core", path = "../vgonio-core" }
