[package]
name = "vgonio"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Microscopic level light transport simulation."
publish = false

[lints]
workspace = true

[features]
default = []

[dependencies]
clap.workspace = true
which.workspace = true
